django_project/first_project/first_app/urls.py
from django.urls import path 
from first_app import views




app_name = 'first_app'

urlpatterns =[

       path('', views.index, name= 'index'),
       path('users/', views.users, name ='users'),
       path('formpage/', views.form_name_view, name= 'formpage'),
       path('register/', views.register, name= 'register'),
       path('userss/', views.user_s, name= 'user_s'),
       path('user_login/', views.user_login, name='user_login'),
      
       
          
          

]



# urlpatterns=[
   
#     url(r'^$', views.index, name='index'),

#     url(r'^topics/$', views.topics, name ='topics'),

#     url(r'^topics/(?P<topic_id>\d+)/$', views.topic , name='topic'),

#     url(r'^java/$', views.java, name ='java_test'),



# ]

django_project/first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.urls import include

urlpatterns = [

    # url(r'^$', views.index, name='index'),
    # url(r'^first_app/',include('first_app.urls')),
    # url(r'^user/',include('first_app.urls')),
    path('', include('first_app.urls' )),
    path('admin/', admin.site.urls),
    path('special/',views.special, name= 'special'),
    path('logout/',views.user_logout, name='logout'),
   
   



]


# url(r'', include(('learnin_logs.urls', 'learnin_logs'),namespace='learnin_logs') ),

django_project/first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.
class Topic(models.Model):
	top_name = models.CharField(max_length = 264, unique= True)


	def __str__(self):
		return self.top_name


class Webpage(models.Model):
	topic = models.ForeignKey( Topic, on_delete= models.CASCADE)
	name = models.CharField(max_length=264, unique=True)
	url = models.URLField(unique=True)

	def __str__(self):
		return self.name


class AccessRecord(models.Model):
	webpageName = models.ForeignKey(Webpage, on_delete= models.CASCADE)
	date = models.DateField()

	def __str__(self):
		return str(self.date)

class Userr(models.Model):
	First_Name = models.CharField(max_length = 264 )
	Last_Name = models.CharField(max_length = 264 )
	Email_Address = models.EmailField(max_length = 264)


	def __str__(self):
		return str(self.First_Name)


class UserProfileInfo(models.Model):
	user = models.OneToOneField(User, on_delete= models.CASCADE)

	portfolio_site = models.URLField(max_length=264, blank=True)
	profile_pic= models.ImageField(upload_to = 'profile_pics',blank=True)

	def __str__ (self):
		return self.user.username

django_project/first_project/first_app/forms.py
from django import forms
from django.core import validators
from first_app.models import  UserProfileInfo , Userr
from django.contrib.auth.models import User 







def check_for_z(value):
	if value[0].lower() != 'z':
		raise forms.ValidationError('name needs to star with z')


class FormName(forms.Form):
	name = forms.CharField(validators = [check_for_z])
	email = forms.EmailField()
	verify_email = forms.EmailField(label= 'Enter your email again:')
	text = forms.CharField(widget = forms.Textarea)
	botcatcher= forms.CharField(required= False,
                                 widget= forms.HiddenInput,
		                         validators=[validators.MaxLengthValidator(0)])

	def clean(self):
		all_clean_data = super().clean()
		email = all_clean_data['email']
		vmail = all_clean_data['verify_email']

		if email != vmail:
			raise forms.ValidationError('make sure emails match')



class NewUserForm(forms.ModelForm):
	class Meta():
		model = Userr
		fields = '__all__'



class UserForm(forms.ModelForm):
	password = forms.CharField(widget= forms.PasswordInput())
	class Meta:
		model = User
		fields = ('username','email','password')



class UserProfileInfoForm(forms.ModelForm):
	
	class Meta:
		model = UserProfileInfo
		fields = ('portfolio_site', 'profile_pic')






    

django_project/first_project/first_app/views.py
from django.shortcuts import render, redirect
from first_app.models import AccessRecord,Topic,Webpage,Userr 
from first_app.forms import FormName, UserForm, UserProfileInfoForm, NewUserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
# from django.urls import reverse




# Create your views here.




def index(request):
	Webpages_list = AccessRecord.objects.order_by('date')
	context = {'access_records':Webpages_list}
	return render(request,'first_app/index.html', context)

def user_s(request):
	users_list = Userr.objects.all()
	users_dict = {'users_info':users_list}
	return render(request,'first_app/user_s.html', context= users_dict )


def form_name_view(request):
	form = FormName()

	

	if request.method == 'POST':
		form = FormName(request.POST)
		if form.is_valid():
			print ('name:  '+form.cleaned_data['name'])
			print ('email: '+form.cleaned_data['email'])
			print ('text:  '+form.cleaned_data['text'])

	return render(request, 'first_app/form_page.html',{'form':form})


def users(request):
	form = NewUserForm()
	if request.method == "POST":
		form = NewUserForm(request.POST)


		if form.is_valid():
			form.save()
			return index(request)
			# return redirect('first_app:index')
		else:
			print('Error form invalid')

	return render(request,'first_app/users.html',{'form':form})



def register(request):
	registered = False 

	if request.method =='POST':
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile= profile_form.save(commit= False)
			profile.user= user 

			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']

			profile.save()

			registered = True
		else:
			print(user_form.errors,profile_form.errors)

	else:
		user_form=UserForm()
		profile_form=UserProfileInfoForm

	return render (request,'first_app/registration.html',
		                    {'user_form':user_form,
		                     'profile_form':profile_form,
		                      'registered':registered})





def user_login(request):
	if request.method =="POST":

		username= request.POST.get('username')
		username.upper()
		password= request.POST.get('password')
		user= authenticate(username =username , password= password)
		if user:
			if user.is_active:
				login(request,user)
				return redirect('first_app:index')
			else:
				return HttpResponse('Account Not Active')
	else:
		print('someone tried to login and failed!')
		# print('username:{} and password:{}'.format (username,password))
		return render(request, 'first_app/login.html')




@login_required
def special(request):
    return HttpResponse ('You are logged out')




@login_required
def user_logout(request):
	logout(request)
	return redirect('first_app:index')

django_project/first_project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>BASE.HTml</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>

<body>

  <nav class= 'navbar  navbar-default navbar-static-top'>
  	<div class= 'container'>
  	 <ul class= 'nav navbar-nav'>
  	  
  	 <li><a class= 'navbar-brand' href =  '{% url "first_app:register" %}'>Register</a></li>
    <li> <a class= 'navbar-brand' href = '{% url "admin:index" %}'>Admin</a></li>
    <li><a class= 'navbar-brand' href = '{% url "first_app:index" %}'>DJANGO</a></li>


    {% if user.is_authenticated %}    
    <li> <a class= 'navbar-brand' href= '{% url 'logout' %}'>Logout</a></li>
     
      {%else%}
      <li> <a class= 'navbar-brand' href= "{%url 'first_app:user_login'%}"> Login</a></li>
     
       
     {%endif%}
     
  	</ul>
  </div>
</nav>

<div class= "container">
  {%if user.is_authenticated%}
  <h1>Hello {{user.username}}, <br> <br>Welcome back</h1> 
   
  {%endif%}
</div>
  
  <div class= "container">
  	{%block body_block%}
  	{%endblock%}
  </div>


  
 
</body>
</html>

django_project/first_project/templates/first_app/form_page.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Forms</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

  </head>
  <body>
    <a href = '{% url "first_app:users" %}'> go to users page</a>
     <a href = '{% url "admin:index" %}'> go to admin </a>
     <a href = '{% url "first_app:index" %}'> go to index </a>
    <h1> fill out the form </h1>

    <div class = "container">

    <form method ="POST">

        {{form.as_p}}

        {%csrf_token%}
        

    <input type="submit" class="btn btn-primary"  value="submit" >

    </form>

    </div>
    </body>
    </html>

  

django_project/first_project/templates/first_app/index.html
<!DOCTYPE html>
{%extends "first_app/base.html" %}

{%block body_block%}
<div class = 'jambotron'>
{%if user.is_authenticated%}
<h1></h1>
{%else%}
	<h1> You have been logged out  </h1>
	{%endif%}
</div>

{%endblock%}

{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Django Level Two</title>
    <link rel= "stylesheet" href="{%static 'css/styles.css' %}"/>
  </head>
  <body>
    <h1> Hi Welcome to Django Level Two</h1>
    <h2> Here are your access records:</h2>
     <a href = '{% url "first_app:formpage" %}'> go to form page</a>

    <div class= "djangotwo">
    	{%if access_records%}
    	<table>
    	  <thead>
    	  	<th>Site Name</th>
    	  	<th>Date Access</th>
    	  </thead>

    	  {%for acc in access_records%}
    	<tr>
    	  <td>{{acc.name}}</td>
    	  <td>{{acc.date}}</td>
    	</tr>
    	{%endfor%}

    	</table>
    	{%else%}
    	 <p> No Access Records Found!</p>
    	 {%endif%}

   </div>

 </body>
</html>

django_project/first_project/templates/first_app/login.html
{%extends 'first_app/base.html'%}

{%block body_block%}

<div class ='jumbotron'>
<h1> Please Login</h1>
<form action="{%url 'first_app:user_login'%}" method= 'post'>
	{%csrf_token%}
	<label for='username' >Username:</label>
	<input type='text' name='username' placeholder="Enter Username">

	<label for='password'>Password</label>
	<input type='password' name='password'>
	<input type='submit'  value='login'>
 
</form>
</div>

{%endblock%}

django_project/first_project/templates/first_app/registration.html
<!DOCTYPE html>

{%extends "first_app/base.html" %}


{%block body_block%}


<div class= 'jumbotron'>
	{% if registered   %}
	<h1>Thank you for registering</h1>

	{%else%}
	<h1> Register Here!</h1>
	<h3> Fill out form</h3>

	<form method= "post" enctype="multipart/form-data">
		{%csrf_token%}
		{{user_form.as_p}}
		{{profile_form.as_p}}

	<input type = "submit"  name = ""  value="Register">
</form>

	{%endif%}
</div>
{%endblock%}

django_project/first_project/templates/first_app/user_s.html
{%extends "first_app/base.html" %}

{%block body_block%}

{{users_info}}

{%endblock%}

django_project/first_project/templates/first_app/users.html
{%extends "first_app/base.html"%}
{%block body_block%}


<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Forms</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

  </head>
  <body>
    

    <div class = "container">
<h1> fill out the form </h1>
    <form method ="POST">

        {{form.as_p}}

        {%csrf_token%}
        

    <input type="submit" class="btn btn-primary"  value="submit" >

    </form>

    </div>
    </body>
    </html>

{%endblock%}